import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import EntryText from "../components/1_startseite/entryText";
import References from "../components/1_startseite/References";
import VideoHead from "../components/1_startseite/VideoHead";
import Carousel from "../components/1_startseite/Carousel";
import Werwirsind from "../components/1_startseite/Werwirsind";
import Grid from "../components/1_startseite/grid";

const Home: NextPage = () => {
  const Referenzen1 = [
    {
      title: "Imagefilm",
      image: "/images/referenzen/Film/Wessendorf.jpg",
      link: "/leistungen/imagefilme",
    },
    {
      title: "Tourismus",
      image: "/images/referenzen/Film/om_freizeit.jpg",
      link: "",
    },
    {
      title: "Spot",
      image: "/images/referenzen/Film/vr_spot.png",
      link: "",
    },
    {
      title: "Unternehmensfilm",
      image: "/images/referenzen/Film/behrens-meyer-besucher-min.png",
      link: "",
    },
  ];

  const Referenzen2 = [
    {
      title: "Recruiting",
      image: "/images/referenzen/Film/ihk-min.png",
      link: "",
    },
    {
      title: "Event",
      image: "/images/referenzen/Film/bni-2019-recap-min.png",
      link: "",
    },
    {
      title: "Produktfilm",
      image: "/images/referenzen/Film/Kröger-Mulde.jpg",
      link: "",
    },
    {
      title: "Portrait",
      image: "/images/referenzen/Film/preisträger-lebenswerk-min.png",
      link: "/leistungen/portrait",
    },
  ];

  return (
    <>
      <Head>
        <title>Wohlfarth Film</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="">
        <VideoHead />
        <EntryText />
        <Grid />

        <References items={Referenzen1} />
        <Werwirsind />
        <References items={Referenzen2} />
      </main>
    </>
  );
};

export default Home;
