import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import EntryText from "../components/1_startseite/entryText";
import References from "../components/1_startseite/References";
import VideoHead from "../components/1_startseite/VideoHead";
import Carousel from "../components/1_startseite/Carousel";
import Werwirsind from "../components/1_startseite/werwirsind";

const Home: NextPage = () => {
  const Referenzen1 = [
    {
      title: "Imagefilm",
      image: "/images/ref2.jpg",
      link: "",
    },
    {
      title: "Tourismus",
      image: "/images/ref2.jpg",
      link: "",
    },
    {
      title: "Spot",
      image: "/images/ref2.jpg",
      link: "",
    },
    {
      title: "Unternehmensfilm",
      image: "/images/ref2.jpg",
      link: "",
    },
  ];

  const Referenzen2 = [
    {
      title: "Recruiting",
      image: "/images/ref2.jpg",
      link: "",
    },
    {
      title: "Event",
      image: "/images/ref2.jpg",
      link: "",
    },
    {
      title: "Produktfilm",
      image: "/images/ref2.jpg",
      link: "",
    },
    {
      title: "Portrait",
      image: "/images/ref2.jpg",
      link: "",
    },
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <VideoHead />
        <Carousel />
        <EntryText />
        <References items={Referenzen1} />
        <Werwirsind />
        <References items={Referenzen2} />
      </main>
    </>
  );
};

export default Home;
